- package.json
- src/process_engine_adapter.ts
**Requires**: https://github.com/process-engine/process_engine/pull/53
Closes #10 
Adds functionality, which allows to wait for a specific EndEvent.
Run the integrationtests.
> Implement functionality to wait for a specific end event

- package.json
- src/process_engine_adapter/process_engine_adapter.ts
- Update all dependency major versions.
- Remove unused references and imports 
> WIP: Feature/update major for data model dependencies

- src/process_engine_adapter/process_engine_adapter.ts
Remove some unused code and fix some typos.
Everything should work as before.
> Remove unused code

- ioc_module.js
- package.json
- src/consumer_api_service.ts
- src/converters/process_model_converter.ts
- src/converters/user_task_converter.ts
* refactored `ProcessModelConverter` and `UserTaskConverter` to classes to be able to use dependency injection properly
* implemented evaluation of user task expressions in `UserTaskConverter`
See https://github.com/process-engine/process_engine_meta/pull/126.
> Dynamic user task expressions

- src/converters/user_task_converter.ts
* fixed erroneous default value
> Fix values without expression

- PULL_REQUEST_TEMPLATE.md
- package.json
- src/adapters/process_model_execution_adapter.ts
- src/consumer_api_service.ts
- src/converters/user_task_converter.ts
**Changes:**
Part of the Heatmap Feature.
This will upgrade any and all usages of the `FlowNodeInstanceService` to the new specs
- The `ExecutionContextFacade` is removed, where it is no longer needed
- All converter- and evaluation functions have been updated to deal with the new `FlowNodeInstance` type, which allows for multiple ProcessTokens to be created for a single `FlowNodeInstance`.
Run the integrationtests for the consumer api and/or the process engine.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text …
> ♻️ Feature/store enter and exit token separately

- package.json
- src/converters/user_task_converter.ts
:**Changes:**
Fixes an issue where the wrong flow node instance id is passed to the `FlowNodeInstanceService` to retrieve the flow node instance for a given process token.
Run the user task tests in the process engine meta repository.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...
**Issues:**
Closes …
> 🐛 Feature/fix user task form field parsing

- package.json
- src/converters/user_task_converter.ts
**Changes:**
1. Add the `name` field to the UserTask type.
2. Upgrade gulp to v4.0.0 to close vulnerabilities. 
**Issues**
PR: #68
Request a list of UserTasks and see that each UserTask now has a name attached to it.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: …
> ✨ Add the Name of the UserTask to the resulting UserTask object

- package.json
- src/consumer_api_service.ts
- src/converters/user_task_converter.ts
**Changes:**
1. Add the `FlowNodeInstanceId` to the UserTask datatype.
2. Change the parameter names for the `finishUserTask` UseCase to indicate InstanceIds, not ModelIds.
3. Refactor `finishUserTask` UseCase:
* Split the UseCase into smaller tasks and move each into its own function.
* Avoid using the `getUserTasksForProcessModelInCorrelation` to avoid side effects, like getting more UserTasks than you wanted to.
4. Remove the `_checkIfCorrelationExists` and `_checkIfProcessInstanceExists` checks, since they each performed additional database queries that seriously impacted performance.
* When a `getUserTask` request is made and the given CorrelationId and/or ProcessInstance does not exists, an empty Array is returned now, instead of a 404.
5. Finish UserTasks by the given InstanceIds, …
> ♻️🔒 Use unique ids for UserTask events

- ioc_module.js
- package.json
- src/consumer_api_service.ts
- src/converters/event_converter.ts
- src/converters/index.ts
- src/converters/user_task_converter.ts
**Changes:**
1. Remove unnecessary private properties
2. Implement Event API.
**Issues:**
Closes: #67
PR: #73
> Describe how others can test your changes (you can remove this section for typo fixes etc.)
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: …
> ✨Implement Event API

- package.json
- src/consumer_api_service.ts
**Changes:**
1. Add identity to events
**Issues:**
Related to https://github.com/process-engine/process_engine_runtime/issues/142
PR: #74
- **Have a look at process-engine/process_engine_runtime#151**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: #NumberOfThisPR …
> 🔒 Add Identity to Events

- ioc_module.js
- package.json
- src/consumer_api_service.ts
- src/converters/index.ts
- src/converters/manual_task_converter.ts
**Changes:**
1. Add ManualTask Converter
2. Add ManualTask methods to ConsumerApiService
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/91
PR: #72
---
See the [examples](#example) for inspiration.
> Describe how others can test your changes (you can remove this section for typo fixes etc.)
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …
> ✨Implement ManualTask

- package.json
- src/consumer_api_service.ts
---
**Changes:**
1. Add a function to let the user execute a callback, when the ProcessInstance started.
**Issues:**
Related: https://github.com/process-engine/process_engine_runtime/issues/134
PR: #75
---
See the [examples](#example) for inspiration.
> Describe how others can test your changes (you can remove this section for typo fixes etc.)
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2: …
> ✨ Implement ProcessStarted Notification

- package.json
- src/consumer_api_service.ts
**Changes:**
1. Implement the `bluebird-global` package, so we  can use `Promise<T>` syntax when using Bluebird functions.
2. Implement the new refactored `EventAggregator`.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/184
PR: #77
All should run as before, except that EventSubscriptions now get cleaned up properly.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre> …
> ♻️ Refactor event aggregator

- package.json
- src/adapters/process_model_execution_adapter.ts
- src/consumer_api_service.ts
- src/converters/event_converter.ts
- src/converters/manual_task_converter.ts
- src/converters/process_instance_converter.ts
- src/converters/process_model_converter.ts
- src/converters/user_task_converter.ts
**Changes:**
Update all type references to the new structure used by the `ConsumerApiContracts` package.
PR: #81
This only changes the type imports, so all should run as before.
> ♻️ 💄 Refactor Namespaces and API interfaces

- package.json
- src/adapters/notification_adapter.ts
- src/consumer_api_service.ts
1. Add Events for Call Activities
2. Add Events for Boundary Events
3. Add Events for Intermediate Events
PR: #94
> Related to https://github.com/process-engine/process_engine_runtime/pull/334
> **Have a look at https://github.com/process-engine/bpmn-studio/pull/1412**
> ✨ Add Events for Call Activities, Boundary Events and Intermediate Events

- Jenkinsfile
- package-lock.json
- package.json
- src/adapters/notification_adapter.ts
- src/consumer_api_service.ts
1. Add `onProcessError` notification
2. Only run `npm ci` on Jenkins builds, if the build runs on the `master` or `develop` branch
- This is required for working with feature branches, or else we would have to rewrite the package-lock after every change we make to a referenced dependency
Part of https://github.com/process-engine/process_engine_runtime/issues/348
PR: #97
> ✨Add onProcessError notification

- ioc_module.js
- package-lock.json
- package.json
- src/external_task_service.ts
- src/index.ts
Add service for handling ExternalTasks.
PR: #55
> ✨Import ExternalTaskApi

- package.json
- src/process_model_service.ts
1. Make Payload Optional for StartProcessInstance
Related to process-engine/process_engine_runtime#371
PR: #100
> ♻️ Make Payload Optional for StartProcessInstance

- package.json
- src/adapters/notification_adapter.ts
- src/notiifcation_service.ts
1. Remove all the deprecated `CallActivity` notifications
PR: #104
>  🔥 Remove CallActivity notifications

- package.json
- src/converters/empty_activity_converter.ts
- src/converters/event_converter.ts
- src/converters/manual_task_converter.ts
- src/converters/user_task_converter.ts
2. Adjust the converters to the new correlation contracts
Part of https://github.com/process-engine/process_engine_runtime/issues/404
PR: #105
> ✨ Add Queries for retrieving ProcessInstances
